services:
  quorum-explorer:
    image: consensys/quorum-explorer:e175e0b
    container_name: quorum-explorer
    ports:
      - "25000:25000"
    environment:
      - QE_BASEPATH=/explorer
      - QE_CONFIG_PATH=/app/config.json
      - NODE_ENV=production
      - DISABLE_AUTH=true
      - NEXTAUTH_URL=http://localhost:25000
      - NEXTAUTH_URL_INTERNAL=http://localhost:25000
      - NEXTAUTH_SECRET=bb5c5f6691e81529db5ec1c8ab9e06c7bbb92551e3e26e5d4b2644148de92909
    volumes:
      - ./explorer-config.json:/app/config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
